export const ActionTypes = {
  GET_LIST_EMPLOYEE_REQUEST: "GET_LIST_EMPLOYEE_REQUEST",
  GET_LIST_EMPLOYEE_SUCCESS: "GET_LIST_EMPLOYEE_SUCCESS",
  GET_LIST_LOCATION: "GET_LIST_LOCATION",
  GET_LIST_LOCATION_SUCCESS: "GET_LIST_LOCATION_SUCCESS",
  GET_OTHER_FEATURE_SUCCESS: "GET_OTHER_FEATURE_SUCCESS",
  GET_OTHER_FEATURE: "GET_OTHER_FEATURE",

  //moi
  GET_TOTAL: "GET_TOTAL",
  GET_TOTAL_SUCCESS: "GET_TOTAL_SUCCESS",

  GET_LIST_EMPLOYEE_DATA: "GET_LIST_EMPLOYEE_DATA",
  GET_LIST_EMPLOYEE_DATA_SUCCESS: "GET_LIST_EMPLOYEE_DATA_SUCCESS",

  GET_EMPLOYEE_DATA: "GET_EMPLOYEE_DATA",
  GET_EMPLOYEE_DATA_SUCCESS: "GET_EMPLOYEE_DATA_SUCCESS",
  RESET_EMPLOYEE_DATA: "RESET_EMPLOYEE_DATA",
  RESET_EMPLOYEE_DATA_SUCCESS: "RESET_EMPLOYEE_DATA_SUCCESS",

  ADD_NEW_EMPLOYEE: "ADD_NEW_EMPLOYEE",
  ADD_NEW_EMPLOYEE_SUCCESS: "ADD_NEW_EMPLOYEE_SUCCESS",

  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_SUCCESS: " UPDATE_EMPLOYEE_SUCCESS",

  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_EMPLOYEE_SUCCESS: " DELETE_EMPLOYEE_SUCCESS",

  GET_FORM_DATA: "GET_FORM_DATA",
  GET_FORM_DATA_SUCCESS: "GET_FORM_DATA_SUCCESS",

  UPDATE_FORM: "UPDATE_FORM",
  UPDATE_FORM_SUCCESS: " UPDATE_FORM_SUCCESS",

  RESET_FORM_DATA: "RESET_FORM_DATA",
  RESET_FORM_DATA_SUCCESS: "RESET_FORM_DATA_SUCCESS",

  ADD_REGIST: "ADD_REGIST",
  ADD_REGIST_SUCCESS: "ADD_REGIST_SUCCESS",

  ADD_REGIST: "ADD_REGIST",
  LEADER_ACTION: "LEADER_ACTION",

  // PROMOTE
  GET_PROMOTE_HISTORY_DATA: "GET_PROMOTE_HISTORY_DATA",
  GET_PROMOTE_HISTORY_DATA_SUCCESS: "GET_PROMOTE_HISTORY_DATA_SUCCESS",

  DELETE_PROMOTE: "DELETE_PROMOTE",

  ADD_PROMOTE: "ADD_PROMOTE",

  UPDATE_PROMOTE: "UPDATE_PROMOTE",

  // SALARY_INCREASE
  GET_SALARY_INCREASE_HISTORY_SUCCESS: "GET_SALARY_INCREASE_HISTORY_SUCCESS",
  GET_SALARY_INCREASE_HISTORY: "GET_SALARY_INCREASE_HISTORY",

  ADD_SALARY_INCREASE: " ADD_SALARY_INCREASE",

  UPDATE_SALARY_INCREASE: "UPDATE_SALARY_INCREASE",

  DELETE_SALARY: "DELETE_SALARY",

  // Proposal Consultation
  GET_PROPOSAL_CONSULTATION: "GET_PROPOSAL_CONSULTATION",
  GET_PROPOSAL_CONSULTATION_SUCCESS: "GET_PROPOSAL_CONSULTATION_SUCCESS",

  ADD_PROPOSACONSULT: "ADD_PROPOSACONSULT",

  UPDATE_PROPOSACONSULT: "UPDATE_PROPOSACONSULT",

  DELETE_PROPOSACONSULT: "DELETE_PROPOSACONSULT",

  // ReleaseManageAction
  RELEASE_MANAGE: "RELEASE_MANAGE",
};
